### ISSUE TITLE
Making Parameters final in constructor

### ISSUE THREAD

**Issue by CharlieHubert** [skiadas/schedule-visualizer#19]
Both parameters inside of the constructor of HCTimeslot are not assigned anywhere outside of the constructor so the error says they can be changed to final. I agree

**Comment by CharlieHubert** [comment]
problem 187/188

**Comment by KMPyle** [comment]
problem 10, 11, 34, 35

**Comment by CharlieHubert** [comment]
See bb772b0d746822a6af408ab1299d7ef4501a1efc
