### ISSUE TITLE
Must use explicit scoping instead of the default package private level in the Conflicts Package

### ISSUE THREAD

**Issue by burchettm26** [skiadas/schedule-visualizer#23]
Problems: 
7 - Instructor Conflict line 8
9 -  Instructor Conflict line 9
24 - Instructor Constraint line 9
40 - TwoCourseConflict line 9
42 - TwoCourseConflict line 10
58 -TwoCourseConstraint line 10
60 - TwoCourseConstraint line 11

**Comment by bayaj0110** [comment]
25b70f64d477d3dd66506fd399d1e51321b3ed14
