### ISSUE TITLE
Clean up Section constructors

### ISSUE THREAD

**Issue by skiadas** [skiadas/schedule-visualizer#33]
Right now the section class has two constructors, one that is given a course and one that is instead given the pieces to create a course. The code for the two constructors seems to also have some repeated work. We need to simplify this, by effectively eliminating the constructor that creates its own course:

- First, rewrite the constructor that creates its own course, so that it doesn't repeat the work that the other constructor does: It should simply use `this(....)` to appropriately call the other constructor. A single line should do this.
- Once you confirm that the above change works, you can now inline this constructor to replace it in all its occurrences. So the various places that were calling on the Section constructor will now do it in two steps, by creating a course then creating a section using this course.

**Comment by CharlieHubert** [comment]
close issue 1c227804445f3d0067d390715f10407fcb97d9a3

**Comment by davidsnowden0072** [comment]
issue closed.
